# Generated by Django 3.2 on 2022-07-18 11:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220714_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
