# Generated by Django 3.0.1 on 2022-08-24 17:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220824_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
